### ISSUE TITLE
Error in  qevd?

### ISSUE THREAD

**Issue by shadrackkibet** [ProjectMOSAIC/mosaic#779]
Why does the following code give an error? 
```
library(extRemes)
mosaic::qdist(dist="evd", p=c(0.1, 0.2, 0.4, 0.6, 0.8, 0.9 ), shape=0, scale=1, loc=0)
Error in qevd(p = c(0, 0.001, 0.999, 1), shape = 0, scale = 1, loc = 0) : 
  qevd: invalid p argument.  Must have 0 < p < 1.
```
I am struggling to understand.

**Comment by rpruim** [comment]
This is caused by `qedv()` not allowing p to be 0 or 1.  Most other q-functions (all I've seen, I think) return a value in that case rather than throwing and error:

```r
qnorm(1)
## [1] Inf
qevd(1)
## Error in qevd(1) : qevd: invalid p argument.  Must have 0 < p < 1.
```

When I get a chance, I'll investigate.  To see if it is easy to avoid, add a work-around, or fail with a better message.

**Comment by shadrackkibet** [comment]
This is confusing bacause the `p` values above i.e `p=c(0.1, 0.2, 0.4, 0.6, 0.8, 0.9 )` are withing range but it still gives an error.

**Comment by rpruim** [comment]
Back at this (finally).  The issue had to do with the values used to create the plot, not the probabilities specified in the call to `qdist()` itself.

I have version that will now work for your example (and for any other distributions that throw an error when p = 0 or p = 1). For good measure, I've also added a new error message in case not enough parameters are specified since my solution to the original concern ended up silently swallowing those.

``` r
suppressPackageStartupMessages(library(extRemes))
mosaic::qdist(dist="evd", p=c(0.1, 0.2, 0.4, 0.6, 0.8, 0.9 ), shape=0, scale=1, loc=0)
#> Registered S3 method overwritten by 'mosaic':
#>   method                           from   
#>   fortify.SpatialPolygonsDataFrame ggplot2
```

![](https://i.imgur.com/A5b8fku.png)

    #> [1] -0.83403245 -0.47588500  0.08742157  0.67172699  1.49993999  2.25036733
    mosaic::qdist('f', (1:5)/5)
    #> Error in dpqrdist(dist, type = "q", p = p, ...): No values could be computed. Did you specify all the required parameters?

<sup>Created on 2022-02-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by rpruim** [comment]
My solution changes the way recycling works.  I'm reopening to see if there is a different solution.

**Comment by rpruim** [comment]
I think my current solution (avoiding purrr::map_dbl() which doesn't recycle the way we might like) is working reasonably well.  Closing.

**Comment by shadrackkibet** [comment]
Good to see that this has been resolved now. Many thanks @rpruim

**Comment by rpruim** [comment]
Hope to get this off to CRAN today (if all goes smoothly with some other things).  Soon in any case.

**Comment by shadrackkibet** [comment]
Superb!

**Comment by Vitalis95** [comment]
Hello, I have tried to run the code but I get the following error;
```
mosaic::qdist(dist="evd", p=c(0.1, 0.2, 0.4, 0.6, 0.8, 0.9 ), shape=0, scale=1, loc=0)
Error in dpqrdist(dist, type = "q", p = c(0, 1e-04, 0.001, 0.01, 0.99,  : 
  No values could be computed. Did you specify all the required parameters?
```

**Comment by Vitalis95** [comment]
Even when I specify all the parameters, the error still persists
```
mosaic::qdist(dist="evd", p=c(0.1, 0.2, 0.4, 0.6, 0.8, 0.9 ), shape=0, scale=1, loc=0,threshold = 0)
Error in dpqrdist(dist, type = "q", p = c(0, 1e-04, 0.001, 0.01, 0.99,  : 
  No values could be computed. Did you specify all the required parameters?
```

**Comment by rpruim** [comment]
@Vitalis95, thanks for reporting this.  I'm not sure exactly what changed, but I think I have a solution.  It's available on github now and I'll see if I can get this to CRAN soon.

If you are willing to install from github (`remotes::install_github('projectMOSAIC/mosaic')`), let me know if it is working for you.

``` r
suppressPackageStartupMessages(library(extRemes))
suppressPackageStartupMessages(library(mosaic))
qdist(dist="evd", p=c(0.1, 0.2, 0.4, 0.6, 0.8, 0.9 ), shape=0, scale=1, loc=0)
```

![](https://i.imgur.com/v8rCopu.png)

    #> [1] -0.83403245 -0.47588500  0.08742157  0.67172699  1.49993999  2.25036733

<sup>Created on 2022-12-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
